### ISSUE TITLE
the function readWithCheck() is strange.

### ISSUE THREAD

**Issue by linkerlin** [Bestoa/shadowsocks-vertx#26]
Sometimes , data is too long to read at one-time.
        mBufferWrap.readWithCheck(local, len);
may fail.

**Comment by Bestoa** [comment]
This method will be used only in blocking mode(parse header and connect to remote). I add this since sometimes the socket is closed and the read return value is -1.
BTW, this class will be removed soon.

**Comment by Bestoa** [comment]
Plan to refine this in this weekend(or next :-x).  For client site, read the header together. then send package one by one.  For server, try to read 512 bytes in header, the non-header data will be stored and send to remote in pre-tcprelay stage.
The server will be changed a lot.

**Comment by Bestoa** [comment]
Done. Currently we don't check the return value of read. Let's do more test.
